name: simple
replicas: 1
namespace: simple
services: 
  - name: a
    workload:
    calls:
      - b
      - c
  - name: b
    workload:
      cpu: 10
    calls:
      - d
  - name: c
    workload:
      cpu: 5
      io: 10
    calls:
      - e
  - name: d
    workload:
      cpu: 5
      io: 10
    calls:
  - name: e
    workload:
      cpu: 10
    calls:
